"""Add last_reset_date to Ponto

Revision ID: 02c21b1aea2d
Revises: d7c36c857fdf
Create Date: 2025-01-15 09:42:36.832328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c21b1aea2d'
down_revision = 'd7c36c857fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.String(length=100), nullable=True),
    sa.Column('pausa', sa.String(length=100), nullable=True),
    sa.Column('retorno', sa.String(length=100), nullable=True),
    sa.Column('saida', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    # ### end Alembic commands ###
