"""Add last_reset_date to Ponto

Revision ID: 426b04e58fc8
Revises: 7a19326c6184
Create Date: 2025-01-14 18:38:28.563504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426b04e58fc8'
down_revision = '7a19326c6184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.drop_column('last_reset_date')

    # ### end Alembic commands ###
