"""atualização

Revision ID: 66be408a1d82
Revises: 
Create Date: 2025-01-19 10:15:08.538793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66be408a1d82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.String(length=100), nullable=True),
    sa.Column('pausa', sa.String(length=100), nullable=True),
    sa.Column('retorno', sa.String(length=100), nullable=True),
    sa.Column('saida', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    op.drop_table('users')
    # ### end Alembic commands ###
