"""Add last_reset_date to Ponto

Revision ID: 680c276f188d
Revises: 426b04e58fc8
Create Date: 2025-01-14 18:44:43.433916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680c276f188d'
down_revision = '426b04e58fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.String(length=100), nullable=True),
    sa.Column('pausa', sa.String(length=100), nullable=True),
    sa.Column('retorno', sa.String(length=100), nullable=True),
    sa.Column('saida', sa.String(length=100), nullable=True),
    sa.Column('last_reset_date', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    # ### end Alembic commands ###
