"""Add last_reset_date to Ponto

Revision ID: d7c36c857fdf
Revises: 680c276f188d
Create Date: 2025-01-14 18:58:26.562830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c36c857fdf'
down_revision = '680c276f188d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.drop_column('last_reset_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_date', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
